# Generated by Django 3.1.4 on 2020-12-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utype',
            field=models.CharField(default='CUS', max_length=3),
        ),
    ]
