# Generated by Django 3.1.4 on 2020-12-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201226_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales',
            field=models.CharField(default='no sales', max_length=100),
        ),
    ]
