# Generated by Django 3.1.4 on 2020-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201226_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
            ],
        ),
    ]
