# Generated by Django 3.1.4 on 2020-12-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20201229_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='apprej',
            field=models.CharField(default='approved', max_length=10),
        ),
    ]
