# Generated by Django 3.1.4 on 2021-01-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20201229_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
