# Generated by Django 3.1.4 on 2021-01-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
