# Generated by Django 3.1.4 on 2021-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
