# Generated by Django 3.1.4 on 2021-01-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20210108_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='optfield1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
