# Generated by Django 3.1.4 on 2021-01-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20210108_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='optfield1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='optfield2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='optfield3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='optfield4',
        ),
    ]
