# Generated by Django 3.1.4 on 2021-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20210111_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='optfield1',
            field=models.CharField(default='New draft', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='optfield2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='optfield3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='optfield4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
