# Generated by Django 3.1.4 on 2021-01-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20210111_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utype',
            field=models.CharField(default='CUS', max_length=3),
        ),
    ]
